class04-08/django_app/askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^weblog/', include('blog.urls', namespace='blog')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

class04-08/django_app/blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^new/$', views_cbv.post_new, name='post_new'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views_cbv.post_edit, name='post_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
    url(r'^sum/(?P<numbers>[0-9/]+)/$', views.mysum, name='mysum'),
]

class04-08/django_app/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.item_list, name='item_list'),
    url(r'^(?P<pk>\d+)/$', views.item_detail, name='item_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.item_edit, name='item_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.item_delete, name='item_delete'),
    url(r'^new/$', views.item_new, name='item_new'),
]

class04-08/django_app/blog/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


def min_length_3_validator(value):
    if len(value) < 3:
        raise ValidationError('3글자 이상 입력해주세요.')


class Post(models.Model):
    author = models.CharField(max_length=20)
    title = models.CharField(max_length=100,
            validators=[min_length_3_validator],
            help_text='이름 3글자만 넣어주세요.')
    photo = models.ImageField()
    content = models.TextField(help_text='Markdown 문법을 지원합니다.')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # return '/weblog/{}/'.format(self.id)
        return reverse('blog:post_detail', args=[self.id])

class04-08/django_app/shop/models.py
from django.db import models
from django.urls import reverse

class Item(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:item_detail', args=[self.id])

class04-08/django_app/blog/forms.py
from django import forms
from .models import Post

'''
class PostForm(forms.Form):
    author = forms.CharField()
    title = forms.CharField()
    content = forms.CharField()
'''

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        # fields = ['author', 'title', 'content']

class04-08/django_app/shop/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

class04-08/django_app/blog/views.py
import datetime
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .forms import PostForm
from .models import Post

def post_list(request):
    qs = Post.objects.all()

    # request.GET['query']
    query = request.GET.get('query', '')
    if query:
        condition = Q(title__icontains=query) | Q(content__icontains=query)
        qs = qs.filter(condition)

    date_list = []
    for i in range(365):
        date = datetime.datetime(2017, 1, 1) + datetime.timedelta(days=i)
        date_list.append(date)

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'query': query,
        'date_list': date_list,
    })


def post_new(request):
    if request.method == 'POST':
        # request.GET
        # request.POST  # POST인자, 파일 제외
        # request.FILES  # POST인자, 파일만
        form = PostForm(request.POST)
        if form.is_valid():
            # form.cleaned_data  # {'title': ??, 'author': ??}
            post = form.save()
            # return redirect('blog:post_detail', post.id)
            return redirect(post)  # post.get_absolute_url()로 이동
        #else:
        #    form.errors
    else:
    # if request.method == 'GET':
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_edit(request, pk):
    post = Post.objects.get(pk=pk)

    if request.method == 'POST':
            # request.GET
        # request.POST  # POST인자, 파일 제외
        # request.FILES  # POST인자, 파일만
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            # form.cleaned_data  # {'title': ??, 'author': ??}
            post = form.save()
            return redirect('blog:post_detail', post.id)
        #else:
        #    form.errors
    else:
        # if request.method == 'GET':
        form = PostForm(instance=post)

    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def post_detail(request, pk):
    # pk = "100"
    post = Post.objects.get(pk=pk)
    return render(request, 'blog/post_detail.html', {
        'post': post,
    })


def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:post_list')
    return render(request, 'blog/post_confirm_delete.html', {
        'post': post,
    })


def mysum(request, numbers):
    # "10/20/30/40/50/60".split("/")

    '''
    result = 0
    for number in numbers.split('/'):
        # 1)
#       if number:
#           result += int(number)

        # 2)
        result += int(number or 0)
    '''

    # 3) generator expression
    result = sum(
        int(number or 0)
        for number in numbers.split('/'))
    return HttpResponse(result)

class04-08/django_app/shop/views.py
from django.shortcuts import redirect, render
from .models import Item
from .forms import ItemForm


def item_list(request):
    return render(request, 'shop/item_list.html', {
        'item_list': Item.objects.all(),
    })


def item_detail(request, pk):
    item = Item.objects.get(pk=pk)
    return render(request, 'shop/item_detail.html', {
        'item': item,
    })


def item_new(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            item = form.save()
            return redirect(item)
    else:
        form = ItemForm()
    return render(request, 'shop/item_form.html', {
        'form': form,
    })


def item_edit(request, pk):
    item = Item.objects.get(pk=pk)

    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save()
            return redirect(item)
    else:
        form = ItemForm(instance=item)
    return render(request, 'shop/item_form.html', {
        'form': form,
    })


def item_delete(request, pk):
    item = Item.objects.get(pk=pk)
    if request.method == 'POST':
        item.delete()
        return redirect('shop:item_list')
    return render(request, 'shop/item_confirm_delete.html', {
        'item': item,
    })

class04-08/django_app/askdjango/templates/layout.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>AskDjango 서비스</title>
<style>
body {
}
</style>
{% block extra_head %}{% endblock %}
</head>
<body>
    <h1>AskDjango</h1>

    {% block logo %}
        <img src="{% static 'python_logo.jpg' %}" style="width: 100px" alt="">
    {% endblock %}

    <hr/>

    {% block content %}
    {% endblock %}

    <hr/>
    &copy; 2017 AskDjango. All rights reserved.
</body>
</html>

class04-08/django_app/blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load static %}

{% block extra_head %}
<style>
</style>
{% endblock %}

{% block logo %}
    <img src="{% static 'blog/django_logo.png' %}" style="width: 100px;" alt="">
{% endblock %}

class04-08/django_app/blog/templates/blog/post_confirm_delete.html
<h1>{{ post.title }}</h1>

<form action="" method="post">
    {% csrf_token %}

    정말 삭제하시겠습니까? 후회없으시죠?
    낙장불입 !!!

    <input type="submit" value="후회없습니다. 삭제하세요." />
</form>

class04-08/django_app/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h1>{{ post.title }}</h1>
    {{ post.content|linebreaks }}
    <hr/>
    <a href="{% url 'blog:post_list' %}">목록으로</a>
    <a href="{% url 'blog:post_edit' post.pk %}">수정하기</a>
    <a href="{% url 'blog:post_delete' post.pk %}">삭제하기</a>
{% endblock %}

class04-08/django_app/blog/templates/blog/post_form.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <form action="" method="post">
                {% csrf_token %}

                {% bootstrap_form form %}

                <input type="submit" value="저장하기" class="btn btn-primary btn-block" />
            </form>

        </div>
    </div>
</div>

class04-08/django_app/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="query" value="{{ query }}" />
        <input type="submit" value="검색" />
    </form>

    <a href="{% url 'blog:post_new' %}">New Post</a>

    <ul>
        {% for post in post_list %}
        <li>
            {{ post.pk }}

            <a href="{% url 'blog:post_detail' post.pk %}">
                {{ post.title }}
            </a>
            <small>({{ post.created_at|timesince }} ago)</small>
        </li>
        {% endfor %}
    </ul>

    <hr/>

    {% for current_date in date_list %}
        {% ifchanged %}
            <h3>{{ current_date|date:"M" }}</h3>
        {% endifchanged %}
        {{ current_date }}<br/>
    {% endfor %}

{% endblock %}

class04-08/django_app/shop/templates/shop/item_confirm_delete.html
<h1>{{ item.name }}</h1>

<form action="" method="post">
    {% csrf_token %}

    후회없죠?
    <input type="submit" value="없습니다. 지우세요." />
</form>

class04-08/django_app/shop/templates/shop/item_detail.html
<h1>{{ item.name }} ({{ item.price }}원)</h1>

{{ item.desc }}

<hr/>

<a href="{% url 'shop:item_list' %}">목록</a>
<a href="{% url 'shop:item_edit' item.id %}">수정</a>
<a href="{% url 'shop:item_delete' item.id %}">삭제</a>

class04-08/django_app/shop/templates/shop/item_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" />
</form>

class04-08/django_app/shop/templates/shop/item_list.html
<ul>
{% for item in item_list %}
<li>
    <a href="{{ item.get_absolute_url }}">
        {{ item.name }}
    </a>
    : {{ item.price }} at {{ item.created_at }}
</li>
{% endfor %}
</ul>

<hr/>

<a href="{% url 'shop:item_new' %}">New Item</a>